comment: Commentaire sur l'entraînement

wandb:
  name_project: "COTS_detection"
  name_run: 

data:
  csv_file: assets/tensorflow-great-barrier-reef/train.csv
  root_path: assets/tensorflow-great-barrier-reef/train_images

configs:
  epoch: 20
  batch_size: 2
  seed: 1
  checkpoint:
    monitor: "validation/F2_score"
    mode: "max"
  early_stopping:
    monitor: "validation/F2_score"
    mode: "max"
    patience: 8

model:
  name: model.RetinaNet.RetinaNet
  params:
    pretrained: True
    pretrained_backbone: True

optimizer:
  name: torch.optim.SGD
  params:
    lr: 0.005
    momentum : 0.9

scheduler:
  name: torch.optim.lr_scheduler.ReduceLROnPlateau
  params:
    mode: "max"
    verbose: True
    factor: 0.1
    patience: 5
  monitor: "validation/F2_score"