comment: Commentaire sur l'entraînement

wandb:
  name_project: "COTS_detection"
  name_run: 

data:
  csv_file: ../tensorflow-great-barrier-reef/train.csv
  root_path: ../tensorflow-great-barrier-reef/train_images

configs:
  epoch: 10
  it: 200
  seed: 1
  k_folds: 2
  batch_size: 2
  seed: 1
  checkpoint:
    monitor: "train/loss_sum"
    mode: "min"
  early_stopping:
    monitor: "train/loss_sum"
    mode: "min"
    patience: 4

model:
  name: model.Model.FasterRCNN
  params:
    pretrained: True
    pretrained_backbone: True

criterion: 
  name: torch.nn.CrossEntropyLoss
  params:
    reduction: mean
    
optimizer:
  name: torch.optim.SGD
  params:
    lr: 0.005
    momentum : 0.9

scheduler:
  name: torch.optim.lr_scheduler.MultiStepLR
  params:
    milestones:
      - 500
    gamma: 0.1
