comment: Commentaire sur l'entraînement

task: object_detection

wandb:
  name_project: "COTS_detection"

data:
  csv_file: /home/clement/Documents/Cours/MVA/Cours_to_validate/Deep_learning/Project/tensorflow-great-barrier-reef/train.csv
  root_path: /home/clement/Documents/Cours/MVA/Cours_to_validate/Deep_learning/Project/tensorflow-great-barrier-reef/train_images

configs:
  epoch: 10
  batch_size: 12
  seed: 1

model:
  name: model.Model.FasterRCNN
  params:
    pretrained: False
    pretrained_backbone: False

# criterion:
#   task1: classification
#     name: torch.nn.CrossEntropyLoss
#     params:
#       reduction: mean
#   task2: regression
#     name: torch.nn.MSELoss

optimizer:
  name: torch.optim.SGD
  params:
    lr: 0.001
    momentum : 0.5