comment: Commentaire sur l'entraînement

task: object_detection

wandb:
  name_project: "COTS_detection"

data:
  csv_file: /kaggle/input/tensorflow-great-barrier-reef/train.csv
  root_path: /kaggle/input/tensorflow-great-barrier-reef/train_images

configs:
  epoch: 20
  it: 200
  batch_size: 10
  seed: 1

model:
  name: model.FasterRCNN.FasterRCNN
  params:
    pretrained: True
    pretrained_backbone: True

optimizer:
  name: torch.optim.SGD
  params:
    lr: 0.001
    momentum : 0.9

metrics:
  train:
    - "loss"
    - "IoU"
    - "F2-score"
  validation:
    - "loss"
    - "IoU"
    - "F2-score"
