comment: Commentaire sur l'entraînement

wandb:
  name_project: "COTS_detection"
  name_run: 

data:
  csv_file: ../tensorflow-great-barrier-reef/train.csv
  root_path: ../tensorflow-great-barrier-reef/train_images

configs:
  epoch: 50
  it: 200
  batch_size: 2
  seed: 1
  checkpoint:
    monitor: "train/loss_sum"
    mode: "min"
  early_stopping:
    monitor: "train/loss_sum"
    mode: "min"
    patience: 5
    
model:
  name: model.FasterRCNN.FasterRCNN
  params:
    pretrained: True
    pretrained_backbone: True

optimizer:
  name: torch.optim.SGD
  params:
    lr: 0.005
    momentum : 0.9

scheduler:
  name: torch.optim.lr_scheduler.ReduceLROnPlateau
  params:
    mode: "min"
    verbose: True
    factor: 0.1
    patience: 4
  monitor: "train/loss_sum"